feature/23-setup-oauth-server-github-actions
codenip-tech/brisbane pull request #51
Opened 2022-02-15 22:54 UTC by lologalvez

* Add php-cs-fixer to oauth's php Dockerfile
* Add phpunit-bridge to oauth
* Add oauth checks job to github actions

Fixes #23

2022-02-15 23:04 UTC, lologalvez commented
Technical remarks:

- Added php-cs-fixer to oauth so `make code-style-check` works as expected.
- Added phpunit-bridge to oauth  so `make tests` works as expected (even though there are no tests yet)
- Kept oauth_checks as a separate job from app_checks in .github/workflows/pr.yml because there are slight differences between them:
    - oauth requires copying docker-compose.yml from docker-compose.yml.dist
    - app has a step for copying .env.example to .env that does not apply to oauth (so far)

However, both jobs could be unified later for some common steps

2022-02-16 20:06 UTC, moein commented on make.sh
> +    docker exec --user ${UID} ${DOCKER_BE} php-cs-fixer fix src --rules=@Symfony --dry-run || true
If you add || true for the check then the pipeline won't fail.

2022-02-16 20:12 UTC, moein requested changes

2022-02-16 20:12 UTC, moein commented on oauth/.php-cs-fixer.cache
> +{"php":"8.1.1","version":"3.6.0","indent":"    ","lineEnding":"\n","rules":{"array_syntax":true,"backtick_to_shell_exec":true,"binary_operator_spaces":true,"blank_line_before_statement":{"statements"
Please remove this from your branch and add the file into the root .gitignore

2022-02-16 20:12 UTC, moein commented on .github/workflows/pr.yml
> +      - name: Run tests
You can comment the lines for run tests so you don't have to install phpunit in this PR

2022-02-16 20:12 UTC, moein commented on oauth/composer.json
> +        "symfony/phpunit-bridge": "^6.0",
Please do not include this line in this PR

2022-02-16 20:12 UTC, moein commented on oauth/phpunit.xml.dist
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove this file

2022-02-16 22:07 UTC, lologalvez commented
Updated PR according to changes proposed by @moein

2022-02-23 19:06 UTC, moein approved these changes
Thanks for the contribution @lologalvez

2022-02-23 19:06 UTC, merged